import data from '../data'

const createCharacters = async () => {
  await data.Character.create({
    first_name: 'Harry',
    last_name: 'Potter',
    full_name: 'Harry Potter',
    born: '1980-07-31',
    died: null,
    role: 'Student',
    school_position: null,
    house_position: 'Quiddich Captain',
    school: 'Hogwarts',
    house: 'Gryffindor',
    patronous: 'Stag',
  })
  await data.Character.create({
    first_name: 'Hermione',
    last_name: 'Granger',
    full_name: 'Hermione Granger',
    born: '1979-09-19',
    died: null,
    role: 'Student',
    school_position: null,
    house_position: 'Prefect',
    school: 'Hogwarts',
    house: 'Gryffindor',
    patronous: 'Otter',
  })
  await data.Character.create({
    first_name: 'Ron',
    last_name: 'Weasley',
    full_name: 'Ron Weasley',
    born: '1980-03-01',
    died: null,
    role: 'Student',
    school_position: null,
    house_position: 'Prefect',
    school: 'Hogwarts',
    house: 'Gryffindor',
    patronous: 'Jack Russell Terrier',
  })
  await data.Character.create({
    first_name: 'Ginny',
    last_name: 'Weasley',
    full_name: 'Ginny Weasley',
    born: '1981-08-11',
    died: null,
    role: 'Student',
    school_position: null,
    house_position: null,
    school: 'Hogwarts',
    house: 'Gryffindor',
    patronous: 'Horse',
  })
  await data.Character.create({
    first_name: 'Luna',
    last_name: 'Lovegood',
    full_name: 'Luna Lovegood',
    born: '1981-02-13',
    died: null,
    role: 'Student',
    school_position: null,
    house_position: null,
    school: 'Hogwarts',
    house: 'Ravenclaw',
    patronous: 'Hare',
  })
  await data.Character.create({
    first_name: 'Neville',
    last_name: 'Longbottom',
    full_name: 'Neville Longbottom',
    born: '1980-07-30',
    died: null,
    role: 'Student',
    school_position: null,
    house_position: null,
    school: 'Hogwarts',
    house: 'Gryffindor',
    patronous: 'Non-corporeal',
  })
  await data.Character.create({
    first_name: 'Dean',
    last_name: 'Thomas',
    full_name: 'Dean Thomas',
    born: '1980-01-01',
    died: null,
    role: 'Student',
    school_position: null,
    house_position: null,
    school: 'Hogwarts',
    house: 'Gryffindor',
    patronous: 'Non-corporeal',
  })
  await data.Character.create({
    first_name: 'Seamus',
    last_name: 'Finnigan',
    full_name: 'Seamus Finnigan',
    born: '1980-01-01',
    died: null,
    role: 'Student',
    school_position: null,
    house_position: null,
    school: 'Hogwarts',
    house: 'Gryffindor',
    patronous: 'Fox',
  })
  await data.Character.create({
    first_name: 'Minerva',
    last_name: 'McGonnagal',
    full_name: 'Minerva McGonnagal',
    born: '1935-10-04',
    died: null,
    role: 'Professor',
    school_position: 'Transfiguration Professor',
    house_position: 'Head of House',
    school: 'Hogwarts',
    house: 'Gryffindor',
    patronous: 'Phoenix',
  })
  await data.Character.create({
    first_name: 'Albus',
    last_name: 'Dumbledore',
    full_name: 'Albus Dumbledore',
    born: '1981-06-01',
    died: '1997-06-30',
    role: 'Hogwarts Headmaster',
    school_position: 'Headmaster',
    house_position: null,
    school: 'Hogwarts',
    house: 'Gryffindor',
    patronous: 'Phoenix',
  })
  await data.Character.create({
    first_name: 'Serverus',
    last_name: 'Snape',
    full_name: 'Serverus Snape',
    born: '1960-01-09',
    died: '1998-05-29',
    role: 'Professor',
    school_position: 'Potions Professor',
    house_position: 'Head of House',
    school: 'Hogwarts',
    house: 'Slytherin',
    patronous: 'Doe',
  })
  await data.Character.create({
    first_name: 'Filius',
    last_name: 'Flitwick',
    full_name: 'Filius Flitwick',
    born: null,
    died: null,
    role: 'Professor',
    school_position: 'Charms Professor',
    house_position: 'Head of House',
    school: 'Hogwarts',
    house: 'Ravenclaw',
    patronous: null,
  })
  await data.Character.create({
    first_name: 'Pomona',
    last_name: 'Sprout',
    full_name: 'Pomona Sprout',
    born: null,
    died: null,
    role: 'Professor',
    school_position: 'Herbology Professor',
    house_position: 'Head of House',
    school: 'Hogwarts',
    house: 'Hufflepuff',
    patronous: null,
  })
  await data.Character.create({
    first_name: 'Olympe',
    last_name: 'Maxime',
    full_name: 'Olympe Maxime',
    born: null,
    died: null,
    role: 'Beauxbatons Headmaster',
    school_position: 'Headmaster',
    house_position: null,
    school: 'Beauxbatons',
    house: null,
    patronous: null,
  })
  await data.Character.create({
    first_name: 'Igor',
    last_name: 'Karkaroff',
    full_name: 'Igor Karkaroff',
    born: null,
    died: null,
    role: 'Durmstrang Headmaster',
    school_position: 'Headmaster',
    house_position: null,
    school: 'Durmstrang',
    house: null,
    patronous: null,
  })
}

export { createCharacters }
